### PR TITLE
Add Services Module

### PR DESCRIPTION
**Pull request by nevantan**
Adds the services module and the UG Test API feature to configure it. The module exposes RESTful APIs for the following resources/operations:
- File: create/retrieve/delete for attaching files to content types
- Node: create/update/delete for creating and changing test content
- Taxonomy Term: create/delete for test terms
- User: login/logout/token for admin access

These settings can be verified under Structure > Services and clicking the "Edit Resources" link next to the "testcafe" endpoint. The module is needed to allow the TestCafe test suite to create content on the site to test against.

The resources listed above are subject to the same access controls as the rest of the site, so any modifications require valid account credentials. Attempting to access methods exposed by the API that require authentication will fail out with a 403 forbidden status code if no valid credentials are provided.

### CODE REVIEW

**Comment by brharp** [comment]
I don't think you need to include `ug_testing_api.features.menu_links.inc`. The file is not referenced by `ug_testing_api.info`.

**Comment by brharp** [comment]
What about putting this feature in a "UG Testing" package, to make it clear that the feature is not for production? Just a thought.

**Comment by brharp** [comment]
I get a scary warning under "Services Security update". If we decide that the right remediation in this case is "do nothing" (which I think it is, as the module is just now being introduced), could we consider saving that choice (with Strongarm) so it's clear that no mitigation is required?

**Comment by nevantan** [comment]
Removed `ug_testing_api.features.menu_links.inc` and moved the feature to the UG Testing package.

For the record, this is the error message:
services_error

It is not applicable to us as we have never created accounts through the API using the older version. The "Do nothing" action has been taken so, even though the warning still appears, there is a red line at the top stating it has been dealt with.

**Pull request merged**
