### PR TITLE
Add missing Bootstrap classes to Filtered HTML (UG WYSIWYG)[fixes #842]

### LINKED ISSUE #842: Add bootstrap tab and expand/collapse classes to Filtered HTML text format

### PR DESCRIPTION
**Pull request by tqureshi-uog**
Add missing Bootstrap classes to Filtered HTML (UG WYSIWYG)[fixes #842]

This issue is for resolving https://ccswds.visualstudio.com/Avalon/_workitems/edit/1234

### CODE REVIEW

**Comment by tqureshi-uog** [comment]
@abanuog The easiest way to test this would be to pull templates from this page - https://github.com/ccswbs/hjckrrh/wiki/Style-Guide - and verify they all work under the "Filtered HTML" text format

**Comment by abanuog** [comment]
@tqureshi-uog Most of the templates from the styleguide (including the tabbed layouts) failed. There seems to be a few classes missing from the text format (eg. class="rtecenter"). Please double check and fix any issues, and test it more thoroughly...maybe have Megan do the testing.

**Comment by tqureshi-uog** [comment]
Some classes (e.g. `rtecenter`) are not from Bootstrap but from CKeditor's own stylesheet. They can be restored if inadvertently deleted (or, maybe they were never available in the first place and people had to choose Full HTML to use them - in any event, they should also be whitelisted).

Some media classes are missing and need to be added as well.

As for the tabbed layout, it does work, but the testing process revealed potential points of confusion in the Style Guide instructions. These will be cleared up (i.e. the instructions contained template code broken up with instruction text. There should also be a complete, intact, self-contained template for copypaste convenience)

**Comment by tqureshi-uog** [comment]
@abanuog See https://ccswds.visualstudio.com/Avalon/_backlogs/taskboard/Avalon%5CJan-Apr%202018%5C25-%20Yoda?_a=requirements for revised test plan

**Pull request merged**
