### PR TITLE
[issue#266] Ability to choose to include Summary in News Teaser list view [resolves #266]

### LINKED ISSUE #266: N3- Ability to choose to include Summary in News Teaser list view.

### PR DESCRIPTION
**Pull request by brharp**
Fixes issue #266.

### CODE REVIEW

**Comment by brharp** [comment]
@abanuog the issue and template changes relate to the news feature, but the ug_page view is being modified. Did you mean to add a display to the news view instead?

**Comment by brharp** [comment]
The body field is exposed as a variable ($body) in the preprocess function, but the template file is accessing the field value directory ($fields['field_news_body']->content;). Could the template file be changed to use the $body variable?

**Comment by brharp** [comment]
There are a few lines of code commented out in the preprocess function that should be removed:
  // $href = ...
  // $vars['title'] ...

**Comment by mmafe** [comment]
@brharp Is this going to be included in the May 31st release? OAC is interested in this.

**Comment by brharp** [comment]
Yes, should be.

-----Original Message-----

**Pull request merged**
