### PR TITLE
Issue238 - Link filtered FT3 view via more link to filtered FT2 page (deprecated)

### LINKED ISSUE #238: FT3 - Listing page is not filtered
As an admin, it is possible to change the category by which a featured list teaser is filtered. When you go to "More features" on the filtered view, however, it takes you to a listing page of all features (unfiltered). 

The Trello card states the following under functional tests:  

```
Navigate to the appropiate https://trello.com/c/o1GiTtaa/149-ft2-listing-page-for-featured-item from this view, dependent on the current category (e.g. if teaser list is filtered by "videos", then the resulting listing page of features should also be filtered by "videos"
```

### PR DESCRIPTION
**Pull request by mmafe**
Testing if the pull request works. Fixes #238

### CODE REVIEW

**Comment by brharp** [comment]
capture

Including validation criteria in the page causes vocabulary IDs (not vocabulary names) to be included in the feature. Term validation is already being done in the view (which uses the vocabulary name in the exported code). Is there a way we can turn off term validation in the page configuration, to avoid exporting the vocabulary ID (which may change from site to site?)

**Comment by brharp** [comment]
The page should be in a ug_feature_layouts feature to be consistent with other features.

**Comment by mmafe** [comment]
Updated the file. Moved feature layouts from ug_feature to ug_feature_layouts.

**Comment by mmafe** [comment]
Instead of merging with develop, we're merging with release20151215 now. Closing this pull request. For further information see:

**Pull request closed without merging**
