### PR TITLE
Iss591 ckeditortables

### PR DESCRIPTION
**Pull request by nevantan**
Fix issue #591 

Use Drupal filters to add <div class="table-responsive"></div> around every table.

Included automated test to check for the presence of the responsive wrapper and ensure nested duplicate wrappers are removed. Unit test for the filter function has been added to a new test group "UG Unit Test".

Updated ug_wysiwyg feature to include the ug_filter module as a dependency.

### CODE REVIEW

**Comment by nevantan** [comment]
[(3) #591 Ckeditor - Provide method for allowing clients to insert automatically responsive tables](https://trello.com/c/nJqmLT0d/2076-3-591-ckeditor-provide-method-for-allowing-clients-to-insert-automatically-responsive-tables)

**Comment by brharp** [comment]
Could the filter be simplified by first removing any existing table-responsive divs, and then adding them, rather than removing duplicates? e.g.
```
$text = preg_replace("/<div class=\"table-responsive\">(.*)<\/div>)/s", "$1", $text);
$text = preg_replace("/<table/s", "<div class=\"table-responsive\"><table", $text);
$text = preg_replace("/</table>/s", "</table></div>", $text);
```

**Comment by brharp** [comment]
I'm good with this the way it is.

**Comment by nevantan** [comment]
Discussed with @brharp - no changes are to be made as both solutions are functionally similar enough.

**Comment by tqureshi-uog** [comment]
@nevantan Is there some other step required to get this working? The unit tests pass without issue, but when I manually create a page and add a table to it, the source code remains unchanged - see https://ws-securehst13.cs.uoguelph.ca/tqdev/another-test

**Pull request merged**
