### PR TITLE
Fix: Course Outlines detail page should hide field labels if no Term, Instructor

### LINKED ISSUE #494: CO - Course Outlines detail page should hide field label if no associated content exists (eg. Term, Instructor)
Course Outlines detail page should hide field label if no associated content exists (eg. Term, Instructor).

image

### PR DESCRIPTION
**Pull request by brharp**
Fixes #494.

### CODE REVIEW

**Comment by tqureshi-uog** [comment]
It looks like an actual fix for this issue was never committed. If no such fix exists, it may be possible to use the one I've implemented on this stage site: https://www-stage.uoguelph.ca/csaw/course-outlines/animal-behaviour-zoo4070

**Comment by bdavey07** [comment]
This issue seems to be fixed, a pull request exists on testing https://github.com/ccswbs/testing/pull/8 for a test that proves this.

**Comment by bdavey07** [comment]
Whoops, wrong issue

**Comment by bdavey07** [comment]
@tqureshi-uog I am working on this issue now, what is the fix that you implemented on the stage site?

**Comment by tqureshi-uog** [comment]
@bdavey07 See exported view code below:

`$view = new view();
$view->name = 'co2_info_for_single_course';
$view->description = 'Provides all details for a single course.';
$view->tag = 'default';
$view->base_table = 'node';
$view->human_name = 'CO2 - Detail Page for Course Outline';
$view->core = 7;
$view->api_version = '3.0';
$view->disabled = FALSE; /* Edit this to true to make a default view disabled initially */

/* Display: Master */
$handler = $view->new_display('default', 'Master', 'default');
$handler->display->display_options['use_more_always'] = FALSE;
$handler->display->display_options['access']['type'] = 'perm';
$handler->display->display_options['cache']['type'] = 'none';
$handler->display->display_options['query']['type'] = 'views_query';
$handler->display->display_options['exposed_form']['type'] = 'basic';
$handler->display->display_options['pager']['type'] = 'some';
$handler->display->display_options['pager']['options']['items_per_page'] = '1';
$handler->display->display_options['pager']['options']['offset'] = '0';
$handler->display->display_options['style_plugin'] = 'default';
$handler->display->display_options['row_plugin'] = 'fields';
$handler->display->display_options['row_options']['default_field_elements'] = FALSE;
/* Field: Content: Title */
$handler->display->display_options['fields']['title']['id'] = 'title';
$handler->display->display_options['fields']['title']['table'] = 'node';
$handler->display->display_options['fields']['title']['field'] = 'title';
$handler->display->display_options['fields']['title']['label'] = '';
$handler->display->display_options['fields']['title']['exclude'] = TRUE;
$handler->display->display_options['fields']['title']['alter']['word_boundary'] = FALSE;
$handler->display->display_options['fields']['title']['alter']['ellipsis'] = FALSE;
$handler->display->display_options['fields']['title']['element_label_colon'] = FALSE;
$handler->display->display_options['fields']['title']['link_to_node'] = FALSE;
/* Field: Content: Course code */
$handler->display->display_options['fields']['field_course_code']['id'] = 'field_course_code';
$handler->display->display_options['fields']['field_course_code']['table'] = 'field_data_field_course_code';
$handler->display->display_options['fields']['field_course_code']['field'] = 'field_course_code';
$handler->display->display_options['fields']['field_course_code']['label'] = '';
$handler->display->display_options['fields']['field_course_code']['exclude'] = TRUE;
$handler->display->display_options['fields']['field_course_code']['element_label_colon'] = FALSE;
/* Field: Content: Section */
$handler->display->display_options['fields']['field_course_section']['id'] = 'field_course_section';
$handler->display->display_options['fields']['field_course_section']['table'] = 'field_data_field_course_section';
$handler->display->display_options['fields']['field_course_section']['field'] = 'field_course_section';
$handler->display->display_options['fields']['field_course_section']['label'] = '';
$handler->display->display_options['fields']['field_course_section']['alter']['alter_text'] = TRUE;
$handler->display->display_options['fields']['field_course_section']['alter']['text'] = '<p class="media-condensed"><strong>Code and section:</strong> [field_course_code]*[field_course_section]</p>';
$handler->display->display_options['fields']['field_course_section']['element_label_colon'] = FALSE;
/* Field: Content: Course term */
$handler->display->display_options['fields']['field_course_term']['id'] = 'field_course_term';
$handler->display->display_options['fields']['field_course_term']['table'] = 'field_data_field_course_term';
$handler->display->display_options['fields']['field_course_term']['field'] = 'field_course_term';
$handler->display->display_options['fields']['field_course_term']['label'] = '';
$handler->display->display_options['fields']['field_course_term']['alter']['alter_text'] = TRUE;
$handler->display->display_options['fields']['field_course_term']['alter']['text'] = '<p class="media-condensed"><strong>Term:</strong> [field_course_term]</p>';
$handler->display->display_options['fields']['field_course_term']['element_label_colon'] = FALSE;
$handler->display->display_options['fields']['field_course_term']['type'] = 'taxonomy_term_reference_plain';
/* Field: Content: Course instructor */
$handler->display->display_options['fields']['field_course_instructor']['id'] = 'field_course_instructor';
$handler->display->display_options['fields']['field_course_instructor']['table'] = 'field_data_field_course_instructor';
$handler->display->display_options['fields']['field_course_instructor']['field'] = 'field_course_instructor';
$handler->display->display_options['fields']['field_course_instructor']['label'] = '';
$handler->display->display_options['fields']['field_course_instructor']['exclude'] = TRUE;
$handler->display->display_options['fields']['field_course_instructor']['alter']['alter_text'] = TRUE;
$handler->display->display_options['fields']['field_course_instructor']['alter']['text'] = '<p><strong>Instructor:</strong> [field_course_instructor]</p>';
$handler->display->display_options['fields']['field_course_instructor']['element_label_colon'] = FALSE;
$handler->display->display_options['fields']['field_course_instructor']['type'] = 'text_plain';
/* Field: Content: Course instructor name only */
$handler->display->display_options['fields']['field_course_instructor_1']['id'] = 'field_course_instructor_1';
$handler->display->display_options['fields']['field_course_instructor_1']['table'] = 'field_data_field_course_instructor';
$handler->display->display_options['fields']['field_course_instructor_1']['field'] = 'field_course_instructor';
$handler->display->display_options['fields']['field_course_instructor_1']['ui_name'] = 'Content: Course instructor name only';
$handler->display->display_options['fields']['field_course_instructor_1']['label'] = '';
$handler->display->display_options['fields']['field_course_instructor_1']['exclude'] = TRUE;
$handler->display->display_options['fields']['field_course_instructor_1']['element_label_colon'] = FALSE;
$handler->display->display_options['fields']['field_course_instructor_1']['type'] = 'text_plain';
/* Field: Content: Course instructor url */
$handler->display->display_options['fields']['field_course_instructor_url']['id'] = 'field_course_instructor_url';
$handler->display->display_options['fields']['field_course_instructor_url']['table'] = 'field_data_field_course_instructor_url';
$handler->display->display_options['fields']['field_course_instructor_url']['field'] = 'field_course_instructor_url';
$handler->display->display_options['fields']['field_course_instructor_url']['label'] = '';
$handler->display->display_options['fields']['field_course_instructor_url']['alter']['alter_text'] = TRUE;
$handler->display->display_options['fields']['field_course_instructor_url']['alter']['text'] = '<p><strong>Instructor:</strong> <a href="[field_course_instructor_url-url]">[field_course_instructor_1]</a></p>';
$handler->display->display_options['fields']['field_course_instructor_url']['element_label_colon'] = FALSE;
$handler->display->display_options['fields']['field_course_instructor_url']['empty'] = '[field_course_instructor]';
$handler->display->display_options['fields']['field_course_instructor_url']['hide_empty'] = TRUE;
$handler->display->display_options['fields']['field_course_instructor_url']['click_sort_column'] = 'url';
$handler->display->display_options['fields']['field_course_instructor_url']['type'] = 'link_plain';
/* Field: Content: Details */
$handler->display->display_options['fields']['field_course_body']['id'] = 'field_course_body';
$handler->display->display_options['fields']['field_course_body']['table'] = 'field_data_field_course_body';
$handler->display->display_options['fields']['field_course_body']['field'] = 'field_course_body';
$handler->display->display_options['fields']['field_course_body']['label'] = '';
$handler->display->display_options['fields']['field_course_body']['alter']['alter_text'] = TRUE;
$handler->display->display_options['fields']['field_course_body']['alter']['text'] = '<h2><span class="glyphicon glyphicon-info-sign"></span> Details</h2>
[field_course_body]';
$handler->display->display_options['fields']['field_course_body']['element_label_colon'] = FALSE;
/* Field: Content: Attachments */
$handler->display->display_options['fields']['field_course_attachments']['id'] = 'field_course_attachments';
$handler->display->display_options['fields']['field_course_attachments']['table'] = 'field_data_field_course_attachments';
$handler->display->display_options['fields']['field_course_attachments']['field'] = 'field_course_attachments';
$handler->display->display_options['fields']['field_course_attachments']['label'] = '';
$handler->display->display_options['fields']['field_course_attachments']['alter']['alter_text'] = TRUE;
$handler->display->display_options['fields']['field_course_attachments']['alter']['text'] = '<h2><span class="glyphicon glyphicon-paperclip"></span> Syllabus</h2>
<p>[field_course_attachments]</p>';
$handler->display->display_options['fields']['field_course_attachments']['element_label_colon'] = FALSE;
$handler->display->display_options['fields']['field_course_attachments']['click_sort_column'] = 'fid';
$handler->display->display_options['fields']['field_course_attachments']['type'] = 'file_table';
$handler->display->display_options['fields']['field_course_attachments']['delta_offset'] = '0';
/* Field: Content: Course Website */
$handler->display->display_options['fields']['field_course_website']['id'] = 'field_course_website';
$handler->display->display_options['fields']['field_course_website']['table'] = 'field_data_field_course_website';
$handler->display->display_options['fields']['field_course_website']['field'] = 'field_course_website';
$handler->display->display_options['fields']['field_course_website']['label'] = '';
$handler->display->display_options['fields']['field_course_website']['alter']['alter_text'] = TRUE;
$handler->display->display_options['fields']['field_course_website']['alter']['text'] = '<h2><span class="glyphicon glyphicon-globe"></span> Website</h2>
<p>[field_course_website]</p>';
$handler->display->display_options['fields']['field_course_website']['element_label_colon'] = FALSE;
$handler->display->display_options['fields']['field_course_website']['click_sort_column'] = 'url';
$handler->display->display_options['fields']['field_course_website']['type'] = 'link_url';
/* Sort criterion: Content: Post date */
$handler->display->display_options['sorts']['created']['id'] = 'created';
$handler->display->display_options['sorts']['created']['table'] = 'node';
$handler->display->display_options['sorts']['created']['field'] = 'created';
$handler->display->display_options['sorts']['created']['order'] = 'DESC';
/* Contextual filter: Content: Nid */
$handler->display->display_options['arguments']['nid']['id'] = 'nid';
$handler->display->display_options['arguments']['nid']['table'] = 'node';
$handler->display->display_options['arguments']['nid']['field'] = 'nid';
$handler->display->display_options['arguments']['nid']['default_action'] = 'empty';
$handler->display->display_options['arguments']['nid']['default_argument_type'] = 'fixed';
$handler->display->display_options['arguments']['nid']['summary']['number_of_records'] = '0';
$handler->display->display_options['arguments']['nid']['summary']['format'] = 'default_summary';
$handler->display->display_options['arguments']['nid']['summary_options']['items_per_page'] = '25';
/* Filter criterion: Content: Published */
$handler->display->display_options['filters']['status']['id'] = 'status';
$handler->display->display_options['filters']['status']['table'] = 'node';
$handler->display->display_options['filters']['status']['field'] = 'status';
$handler->display->display_options['filters']['status']['value'] = 1;
$handler->display->display_options['filters']['status']['group'] = 1;
$handler->display->display_options['filters']['status']['expose']['operator'] = FALSE;
/* Filter criterion: Content: Type */
$handler->display->display_options['filters']['type']['id'] = 'type';
$handler->display->display_options['filters']['type']['table'] = 'node';
$handler->display->display_options['filters']['type']['field'] = 'type';
$handler->display->display_options['filters']['type']['value'] = array(
  'course_outline' => 'course_outline',
);

/* Display: Content pane */
$handler = $view->new_display('panel_pane', 'Content pane', 'panel_pane_1');
$handler->display->display_options['allow']['use_pager'] = 0;
$handler->display->display_options['allow']['items_per_page'] = 0;
$handler->display->display_options['allow']['offset'] = 0;
$handler->display->display_options['allow']['link_to_view'] = 0;
$handler->display->display_options['allow']['more_link'] = 0;
$handler->display->display_options['allow']['path_override'] = 0;
$handler->display->display_options['allow']['title_override'] = 'title_override';
$handler->display->display_options['allow']['exposed_form'] = 0;
$handler->display->display_options['allow']['fields_override'] = 0;
$handler->display->display_options['argument_input'] = array(
  'nid' => array(
    'type' => 'panel',
    'context' => 'entity:field_collection_item.archived',
    'context_optional' => 0,
    'panel' => '0',
    'fixed' => '',
    'label' => 'Content: Nid',
  ),
);
`

**Comment by tqureshi-uog** [comment]
@bdavey07 See attached code - it works by selectively rewriting and hiding results, i.e.

**Section and term:** rewrite results of field with proper formatting, hide rewriting if empty

**Instructor:** rewrite results `<p><strong>Instructor:</strong> [field_course_instructor]</p>`, hide rewriting if empty

**Instructor, name only:** this is a plain text field (excluded from display, no rewriting) used for link text, token [field_course_instructor_1]

**Instructor url:** No results text set to [field_course_instructor], hide if empty, hide rewriting if empty. Rewritten output is `<p><strong>Instructor:</strong> <a href="[field_course_instructor_url-url]">[field_course_instructor_1]</a></p>` (that is, if there's no value for instructor url, output the rewritten instructor name contained in token [field_course_instructor] whereas if a value does exist for instructor url, output a link using the Instructor name only token as link text)

[CO2-view-code.txt](https://github.com/ccswbs/hjckrrh/files/937197/CO2-view-code.txt)

**Comment by bdavey07** [comment]
Fix that @tqureshi-uog sent works, created new pull request ccswbs/hjckrrh/pull/724 including the Simpletest committed to this one

**Pull request closed without merging**
