### PR TITLE
Issue 593 - Fix bug with test case 2

### PR DESCRIPTION
**Pull request by nevantan**

### CODE REVIEW

**Comment by nevantan** [comment]
## Original Issue
UG Event test would fail if the day of the week was Friday or Saturday, or it was the last- or second-last day of the month because Case 2 adds two days to the current date. This addition of days could potentially push the event date out of the current week or month.

The fix involved removing assertions that Case 2 was on the week and month views. This was just correcting the code to match the test cases described in the original issue #593.

In the procedure below, the first test sets a baseline (this has always worked), the next two test the event getting pushed out of the current week, and the last test pushes the event out of the current month.

## Test Procedure
1. Set system time to any day other than Friday or Saturday
2. Run UG Event test
3. Set system time to Friday or Saturday
4. Run UG Event test
5. Set system time to the last- or second-last day of the month
6. Run UG Event test

## Expected Results
All tests should succeed.

**Comment by mmafe** [comment]
# Results (Work In Progress)
1. Time set to today: All passes
image

2. Time set to Friday, March 24: Test in progress...

3. Time set to last or second-last day of the month: TBD

**Comment by bdavey07** [comment]
Had errors when running with date set to Saturday, March 18th, could this have been because I picked a date in the past?  Running Thursday, March 30th now, will try Saturday, March 25th after.

**Comment by bdavey07** [comment]
Future Saturday (the 25th) passes all tests, past Saturday (the 18th) fails

**Comment by bdavey07** [comment]
# Updated Test

Tested new commit for date: Saturday March 18th

new fail1
new fail2
new fail3

**Comment by bdavey07** [comment]
# Updated Test

**Comment by nevantan** [comment]
Workaround added as per issue #663, tests now pass:
all_events_pass

**Pull request merged**
