### PR TITLE
[Next] Turn on "Create new revision" by default for all content types (Fixes #180)

### LINKED ISSUE #180: G0 - Ensure that revisions are turned on for all content types in platform
Ensure that revisions is turned on for all content types in platform

### PR DESCRIPTION
**Pull request by mmafe**
Turns on "Create new revision" by default for all content types (Fixes #180)

**Affected content types**
-  events
-  people profiles
-  banners
-  features
-  course outlines
-  faq
-  services
-  webform
-  social

Note that under Default options, "Create new revision" is already turned on for:
- page
- news
- book

# Testing Procedure
- Go to Add content, and then select each content type and check that under "URL path settings", the "Create new revision" checkbox is checked.
-

### CODE REVIEW

**Comment by bdavey07** [comment]
# Testing
Install site, create new content and check that Create new revision is checked for the following content types

- [ ] events
- [ ] people profiles
- [ ] banners
- [ ] features
- [ ] course outlines
- [ ] faq
- [ ] services
- [ ] webform
- [ ] social

**Comment by bdavey07** [comment]
@nevantan Handing this off to you as I am not here for the next sprint to review it

**Comment by mmafe** [comment]
@nevantan @bdavey07 Added "Create new revisions" for book feature

**Comment by bdavey07** [comment]
@mmafe Box for "Create new revision" is still unchecked on book

**Comment by mmafe** [comment]
@bdavey07 I was seeing the same behaviour, however on my test site, the UG Book feature was in an Overridden state. Once I reverted the feature, the "Create new revision" box was checked for book. 

On your test site, can you check if the Book feature is in a default state?

**Pull request merged**
