### PR TITLE
Issue 650 - Add last name search to PP views that are missing it

### PR DESCRIPTION
**Pull request by bdavey07**
Fixes Issue #650 

# Fix
Exposed an existing filter on the PP5 view for last name search, added an exposed last name filter on PP1B (Notable Alumni)

# Testing

- Checkout branch `iss650` look at the views changed to ensure change is as expected and fulfills the issue requirements.  
- Run the UG simpletest automated tests

### CODE REVIEW

**Comment by bdavey07** [comment]
Note: @nevantan I'm still working on this, not ready for your review yet

**Comment by bdavey07** [comment]
Turned on `Use panel path` to fix the search functionality, works as expected when a keyword that exists in one of the last names is entered.  However, when entering a keyword that has no results, rather than showing the `No results found` page as PP1 does,



The view seems to 'Go away'.

**Comment by bdavey07** [comment]
Fixed no results behavior, starting to test again myself

**Comment by nevantan** [comment]
Performed the following manual test:
1. Generated 10 profiles with devel generate
2. Replaced PP1 with PP1B on /people page
3. Searched for first 3 letters of last name from an arbitrary profile generated in step 1
    - Profile appeared as expected
4. Added random letters to previous search so it wouldn't have any results
    - "No results found." message appeared as expected

Automated tests pending.

**Comment by nevantan** [comment]
UG Event automated tests passed.

**Comment by bdavey07** [comment]
@nevantan This branch adds the last name search to PP1B (/people/faces), PP5, and PP5 no images, to see the PP5 view, go to /people, delete the PP1 and add PP5.  All the views seems to be working perfectly now.

**Comment by nevantan** [comment]
Looks like PP1B on `/people/faces`, PP5, and PP5: No Images all have the search field (and it works).

**Comment by bdavey07** [comment]
https://github.com/ccswbs/testing/pull/20 is for this issue, test worked at one point, working on modulating the code currently

**Comment by bdavey07** [comment]
http://demoday-bdavey.c9users.io/iss650/

**Pull request merged**
