### PR TITLE
Book feature

### LINKED ISSUE #232: BK2 - Navigation links aren't visually distinct
image

The links to navigate forward, backwards and up are not easily recognizable as separate links without hovering. To improve usability, they could be spaced out more, underlined separately, put in separate buttons, or anything that makes each of the links more visually distinct from each other.

### PR DESCRIPTION
**Pull request by brharp**
Book feature. Fixes #232 and #233 .

### CODE REVIEW

**Comment by mmafe** [comment]
Branch has been merged with sprint7_20160118 for testing/demo purposes.

**Comment by mmafe** [comment]
Merged with sprint8

**Comment by mmafe** [comment]
Merged with sprint9 branch.

**Comment by mmafe** [comment]
merged with sprint10 branch

**Comment by mmafe** [comment]
merged with sprint11 branch

**Comment by mmafe** [comment]
merged with sprint12 branch

**Comment by mancusop** [comment]
@brharp @mmafe BK feature fails due to a HTML validation error in BK2 - check report for details.
added report to feature board.

## Regarding feature set:
- Cannot seem to add inline images as per feature request.
- BK00 indicated that managers can "change category of featured item list" - unsure of what that means.

**Comment by mmafe** [comment]
Thanks for testing @mancusop!

I believe it's the same validation error as the following issue: https://github.com/ccswbs/hjckrrh/issues/156

Since the issues are not show-stoppers, I'm going to merge book onto the develop branch. We can fix the validation issue in future.

**Pull request merged**
