### PR TITLE
Iss431 - Add Workbench

### LINKED ISSUE #431: Suggest integrating Workbench into the AODA Drupal Platform
Suggest integrating Workbench into the AODA Drupal Platform.
https://www.drupal.org/project/workbench

Both Business and School of Computer Science would be interested in this module.

### PR DESCRIPTION
**Pull request by nevantan**
Fixes #431.

### CODE REVIEW

**Comment by bdavey07** [comment]
# Testing 
## Manual Testing
- Default state allows user with minimum author permission publish content (Off by default)
- Enabling the UG Workbench Access module enables the moderation features
- As an author, I can set the moderation state to published, @nevantan do I need to do anything to the site other than turn on UG Workbench Access? 
rd2

**Comment by bdavey07** [comment]
# Testing
## Manual
- Default state has Workbench and Moderation turned on, all roles have permissions to publish content
- Enabling UG Moderation in features strips publishing option from all roles when creating new content
- To publish, the content must first be saved as a draft or set to needs review, then a site manager or user with publisher permissions can publish
- Editors and authors can only set content to draft or needs review
- Authors can make and edit their own drafts without intervention from site manager, cannot revert content from needs review to draft but can edit content after it has been set to needs review
- Editors can make and edit any content, can set change any content from draft to needs review or vice versa, can unpublished content, make new drafts on any content and cannot publish content
- Publishers and site managers can move any content into any state (draft, needs review, published)
- Easy to turn on and off and workflow is customizable
- This seems to work exactly as expected

## Automated Tests (In Progress)
- Running UG Simpletests

## Additional Notes
- What does the Workbench Access module do?

**Comment by brharp** [comment]
I get an error when enabling the UG Moderation module:
````
Warning: Invalid argument supplied for foreach() in workbench_moderation_states_features_rebuild() (line 76 of /users/u/4/brharp/public_html/sites/all/modules/workbench_moderation/workbench_moderation.features.inc).
Warning: Invalid argument supplied for foreach() in workbench_moderation_transitions_features_rebuild() (line 161 of /users/u/4/brharp/public_html/sites/all/modules/workbench_moderation/workbench_moderation.features.inc).
````

**Comment by brharp** [comment]
After initially merging this branch, all of the content type features show as overridden, because of changes to the node options. If I decide not to enable moderation, do these features stay overridden? If I do decide to enable moderation, do I have to revert all of these features manually?

**Comment by brharp** [comment]
When I enabled the feature, authenticated users were given 'Bypass moderation restrictions' permission.

**Comment by mmafe** [comment]
Workbench added via an alternative branch.

**Pull request closed without merging**
