### PR TITLE
Issue174 - CKEditor accessibility improvements.

### LINKED ISSUE #174: G0 - ckeditor changes- to improve accessibility
The ckeditor continues to be a problem for creating accessible content, and while we may be able to train clients, we should consider doing the following changes to help ensure users create accessible content:

1) Remove defaults from Image/table upon inserting
2) also Consider removing the following options, if possible from the editor:
Image:  Wdith, Height, Border
Table: Border size, width, height, cell spacing, cell padding
3) consider removing the current insert table and insert image options and creating our own custom buttons that insert tables and images properly (using Bootstrap classes only).
4) we may also want to consider getting a license for this too: https://cksource.com/ckeditor/services#accessibility-checker ---
Possibility-limit the output on filter to just appropriate html tags and bootstrap classes.  Other research may be required, look to drupal 8 also?

### PR DESCRIPTION
**Pull request by brharp**
Fixes #174

### CODE REVIEW

**Comment by mmafe** [comment]
Merged with sprint7_20160118 and available on the dev environment for testing.

**Comment by anncesar** [comment]
@brharp these changes are super Brent- I have found one issue that I'm hoping you can fix. When I insert a table the first time, the fields that were removed (such as width and height) do not appear and this is great, but when I right mouse click to edit the table the fields reappear- so far it seems that the same issue is not occuring with image editor.

**Comment by tarnok** [comment]
@anncesar @mmafe  - " Add default classes to image and table dialogs."

This is great, so these changes are merged with the sprint/demo branch and if all works we could probably see them in develop/release in a few weeks? I'm gonna have to remove a few paragraphs soon from the Docs.

**Comment by mancusop** [comment]
@anncesar @mmafe - " Add default classes to image and table dialogs."

This is great, so these changes are merged with the sprint/demo branch and if all works we could probably see them in develop/release in a few weeks? I'm gonna have to remove a few paragraphs soon from the Docs.

**Comment by anncesar** [comment]
@brharp so there are actually 2 changes here and I think we are good:
- [ ] add table-responsive class instead of just table
- [ ] fix bug with table unwanted fields on edit of existing table (as per comment above)

**Comment by brharp** [comment]
Inserting a table and editing a table use different dialog boxes, which explains why the height, width, etc. came back when editing an existing table. I have removed the controls from both dialogs now.

**Comment by mmafe** [comment]
Merged with sprint8

**Comment by mmafe** [comment]
Tested on local machine. Works very well. :)

**Findings**
- image includes img-responsive class
- images have removed width, height, border input fields; 
- tables include table and table-responsive classes
- tables have removed border, alignment, width, height, cellspacing, cell padding
- link dialogue no longer shows "Browse Server" button

**Comment by mancusop** [comment]
Will this be pushed for Feb 9th release?

**Comment by mmafe** [comment]
Merged with sprint9 branch.

**Pull request merged**
