### PR TITLE
New: Add FAQ, FAQ category/keyword migration (UG Migrate D6)[fixes #358]

### LINKED ISSUE #358: Migrate D6 - Implement FAQ migration from D6 to D7 site
Implement classes to migrate FAQ, FAQ category, and FAQ terms (for cases where terms exist as a separate vocabulary on the source site) for drupal 6 to drupal 7 sites.

### PR DESCRIPTION
**Pull request by mmafe**
Implements FAQ, FAQ category and FAQ keyword migration from Drupal 6 to Drupal 7 sites.

Works well on local machine migration. Recommend testing migration using data from CIO.

Fixes #358

### CODE REVIEW

**Comment by mmafe** [comment]
Screenshots from local test. Category, keyword, text, question, and answer came through.

image

**Comment by mmafe** [comment]
Merged with sprint11 branch for testing purposes.

**Comment by mmatthews** [comment]
@mmafe
Tested UGFAQ6 from CIO Legacy database to my sandbox at aoda.test.web.uoguelph.ca/mmatthews

Everything came through including category, although it seems format didn't come though as Text format is set to plain text with HTML markup being shown on the front-end.
faq

**Comment by mmafe** [comment]
On local machine migration, format is coming through. I'll dig a bit deeper into CIO to see if we need to add anything extra to get the format showing up...

screenshot at mar 09 14-52-02

**Comment by mmafe** [comment]
SIte appears to be using a module called FAQ (https://www.drupal.org/node/1451186) to generate their faqs somehow...

...wondering if this might have to do with why the format is not coming through.

**Other Observations**
- Format is still showing up in the node_revisions table
- Format is coming through on UGPage
- Worst comes to worst, we could go into the destination site and switch all the FAQs in the database to full_html instead of plain_text. There's definitely a query for that.

**Comment by mmafe** [comment]
Since...

a) format is coming through on local machine,
b) we are able to update CIO format with an SQL query (```UPDATE field_data_field_faq_answer SET field_faq_answer_format = 'full_html' WHERE field_faq_answer_format = 'plain_text';```), and
c) migrate does not affect live sites
d) we need this for migrating CIO faq

...I'm considering this tested and ready for merging with develop so we can use it on the CIO migration.

**Pull request merged**
