### PR TITLE
Issue314 - Implement people profiles feature

### PR DESCRIPTION
**Pull request by brharp**
Implementation of the people profiles feature. Addresses #314 .

### CODE REVIEW

**Comment by mmafe** [comment]
Branch has been merged with sprint7_20160118 for testing/demo purposes.

**Comment by anncesar** [comment]
Some change/fixes, we should discuss anything that doesn't make sense before doing...

Profile content page and view
- [ ] Set default taxonomy Role values to match spec: Default roles are Staff, Faculty, Adjunct Faculty, Sessional, Grad Student, Post Doc, Professor Emeritus/Emerita.
- [ ] Change vocabulary titles to show they are part of the Profile feature- role to Profile Role, Unit to Profile Unit, sub-unit- to Profile sub-unit
- [ ] Unit may need to be a multi-select list? (perhaps hold on this one for now)
- [ ] Page layout for profile detail pages should match others- should be 3 column.  This will allow for us to add 'Find profiles by keyword' view to right region.  So, it would be Profile image in left, node being viewed content in middle, etc.
- [ ] Turn on option in View for website Manager role only to be able to do 'field overrides' - I think this will allow some flexibility for Managers remove fields from display that they may not want across all users.

Profile LIsting page
- [ ] Allow Manager to choose category of listing view to display 
- [ ] Spec says Managers should be able to turn off images from listing view- is that complete?- not checked off as done, but should be an option
- [ ] Don't display role field in listing view

**Comment by mmafe** [comment]
Merged with sprint8

**Comment by Samana04** [comment]
PP1- Listing Page for Multiple Profile Pages Testing result:
- Alt text not appearing when inserting an image and typing the "image caption" 
- Suggestion: The extension option is not available as depicted in the PP1 sample image.

**Comment by brharp** [comment]
Re: "Turn on option in View for website Manager role only to be able to do 'field overrides'" -- the profile detail page is not using a view, so the 'field overrides' do not apply here. As it stands, sites may leave fields blank that they don't wish to use.

**Comment by brharp** [comment]
The option to filter by category was already included in the view, but the people page was not set to use the panels in place editor (so the option was not available to site managers). This has been fixed.

**Comment by mancusop** [comment]
@brharp @mmafe 
# Issues
## PP1
- [ ] - Name of Person incorrectly displayed/formatted. Only formatted as "Display name", no last name or preferred name shown.
- [ ] - Sorting alphabetically doesn't work as described, might have to do with previous issue.
- [ ] - Ability to Search By Last name doesn't work because Last name appears to not be displayed.

## PP1B
- [ ] Entire feature breaks when "preferred name" is too long. No automatic cutoff so you get items on single lines. 

facesbreaking

- [ ] - No Role filter enabled
- [ ] - Heading view says "Profiles" not "Our People" as per Doc.
- [ ] - Alt tags missing according to achecker report.

## PP2
- [ ] - Only Shows preferred name.
- [ ] - Title not Formatted as indicated
- [ ] - Doc says more than one sub-unit can be shown, only one is allowed to be selected in profile creation.
- [ ] - Details are shown but there are no formatting limits - max 255 charas allowed. i.e. Phone numbers and lab locations can be a long string of gibberish.

**Comment by brharp** [comment]
Enabled field overrides (where possible to do so).

**Comment by mmafe** [comment]
Merged with sprint9

**Comment by mmafe** [comment]
merged with sprint10 branch

**Comment by mmafe** [comment]
This branch may have commits from sprint10 merged into the individual branch. May need to uncouple these commits.

**Comment by mmafe** [comment]
Recommend removing the following commit (https://github.com/ccswbs/hjckrrh/commit/a15ef17a6436a0a6698803a98193a78637b3a458) before merging with develop. Otherwise we're bringing in all the sprint testing code as well...

**Comment by brharp** [comment]
Created new branch (ug_profile).

**Pull request closed without merging**
