### PR TITLE
Issue 431 - Workbench

### PR DESCRIPTION
**Pull request by nevantan**
Fixes issue #431.

### CODE REVIEW

**Comment by nevantan** [comment]
[(2) #431 - Moderation Feature - Integrating Workbench into the AODA Drupal Platform](https://trello.com/c/e8IJMVHK/2172-2-431-moderation-feature-integrating-workbench-into-the-aoda-drupal-platform)

**Comment by mmafe** [comment]
Simpletest results: All passed
image

Next testing will be to stage and try out the tool.

**Comment by mmafe** [comment]
Added Workbench and Workbench Moderation. Continuing with testing.

**Comment by mmafe** [comment]
# Further Results

- [ Good ] Staged sites show UG Workbench as disabled 
- [ Good ] Newly installed sites show UG Workbench as enabled

**Comment by bdavey07** [comment]
# Testing

## Manual Testing (In Progress)

- Test the acceptance criteria from issue #431 to ensure they are met
- Read through documentation to ensure it is correct/makes sense
- Go through work flow process, testing all types of content and fringe cases, ensuring the tool works as expected

## Acceptance Criteria

1. Site managers must have ability to turn on and off moderation. Editors and authors cannot turn this on or off. 
    - Create users with each of these different roles
    - Login as editor/author and ensure I cannot turn off moderation
    - Login as site manager and ensure I can turn off moderation 
2. Site managers should have the ability to set up all content that is updated to reviewed by default.   
    - Log in as site manager and ensure this is possible
3. If possible there should be possibility of customizing the standard workflow "Draft--> Needs Review --. Published" . 
    - Log in as admin and see if this is possible 
    - Log in as site manager and see if this is possible

## Automated Testing (In Progress) 

- Run UG Simpletest suite
- Testing in progress on commit 6def91ef

**Comment by bdavey07** [comment]
# Feedback 

When adding content as an author, I would take the following steps
- Go to my workbench (or add content)
- Create a page
- Moderation set to draft (or needs review)
- Save
- Page is created
- Go back to my workbench
- Go to my drafts
- Page created does not show up in my drafts

It seems that as an author, I am not able to edit my drafts until the site manager publishes it.  After it is publish, I can add a new draft to the page and edit the page.  Is this by design or an issue with the platform?

**Comment by nevantan** [comment]
New pull request created, closing this one.

**Pull request closed without merging**
