### PR TITLE
Issue 747 - Update breadcrumbs to be consistent with our test cases

### LINKED ISSUE #747: Use TestCafe Tests to Fix Breadcrumbs
Consider which single breadcrumbs module to use.

Use tests from ccswbs/testing#27 for TDD on breadcrumbs.

### PR DESCRIPTION
**Pull request by nevantan**
Resolves #747.

These changes should be consistent with test cases produced by https://github.com/ccswbs/testing/issues/28.

See ccswbs/testing#38 for testing.

### CODE REVIEW

**Comment by bdavey07** [comment]
Running the new tests for breadcrumbs in ccswbs/testing/pull/38 all pass

**Comment by bdavey07** [comment]
All Simpletests pass

**Comment by nevantan** [comment]
Separate out the patch for Services module from this pull request.

**Comment by mmafe** [comment]
Sidenote: In future, for branches related to hjckrrh, the title of the branch should match the issue number on hjckrrh as opposed to testing. So in this case, instead of iss27, this would be iss747 to prevent confusion with the actual hjckrrh issue 27.

**Comment by mmafe** [comment]
# WIP Testing

## News

1. News node with a news category set results in ```Home / News / <category name>```. This does not match with the following test case.

```
  Scenario: News details page includes the proper links in the breadcrumb
    Given path breadcrumbs is enabled and configured
      And a news node [news] with node ID [nid]
    When  the /node/[nid] page is viewed
    Then  the page title should be "[news]"
      And the breadcrumbs should display only the 'Home' and 'News' links
```

**Comment by bdavey07** [comment]
**Update:** All of the tests are working on ccswbs/testing/pull/38, currently reviewing the code

**Pull request closed without merging**
