### PR TITLE
Issue 548 - Add print module, TCPDF library, and features

### PR DESCRIPTION
**Pull request by nevantan**
Issue #548 

HR temp fix into a feature. Requires more work to add print icon in place of links and to fix up the printer-friendly layout.

### CODE REVIEW

**Comment by nevantan** [comment]
Print icon added, removed footer from print-friendly layout.

**Comment by tqureshi-uog** [comment]
@nevantan Discussed one remaining glitch with @brharp and he agrees it should be fixed before we merge this - the Print module bases print-friendly layouts on Node Display, not Page Manager. As a result, field labels (e.g. "Body") are showing up on certain content types (e.g. basic Page, Event) in print-friendly mode. Please check "Manage Display" for all relevant content types to ensure unwanted field labels are set to "Hidden" mode.

**Comment by nevantan** [comment]
[#548 - Fix printer-friendly page formatting](https://trello.com/c/vdqvjoBi/2126-548-fix-printer-friendly-page-formatting)

**Comment by nevantan** [comment]
Rechecked content types.

**Banner:** No change - not displayed.

**Course outline:**
- Reordered fields to match standard layout
- Removed fields that don't appear on standard layout
- Removed redundant "Attachment" label
- Left other labels, there is enough information that they are required for readers to make sense of the content

**Event:**
- Reordered fields
- Removed Category field
- Removed some extraneous labels
- Added ug_theme_field__field_event_heading to template.php to wrap section headers in <h3>

**FAQ:**
- Removed Category and Keyword fields as they don't seem relevent (and don't appear on the standard layout
- Removed "Answer" label

**Feature:** No change - not displayed.

**News:**
- Reordered fields
- Removed Category field

**Page:**
- Removed Body label
- Removed Keywords field

**Profile:** Skipping for now as it doesn't have a print link and it is having custom fields added. May revisit in future. Note: Profile has a number of fields hidden, so current print layout (/print/[tid]) looks strange.

**Service:**
- Fixed Internal Notes headers and links

**Pull request merged**
