### PR TITLE
Issue#266

### PR DESCRIPTION
**Pull request by abanuog**
Added a new display for News, which allows showing the summary.

### CODE REVIEW

**Comment by mmafe** [comment]
Merged with sprint9 branch.

**Comment by mancusop** [comment]
@mmafe is my sandbox https://aoda-web.uoguelph.ca/sandbox_pj/ part of the sprint9 branch? Can't seem to find the N3 summary view.

**Comment by mmafe** [comment]
@mancusop Yup, the sandbox is running sprint9 which includes this branch. (Just checked the code). I've set the label back to "Needs Development." You can move onto the next item in need of testing.

@abanuog Hey Joy, could you please check to see if the N3 summary display was exported as part of the UG News view? With the current commits, I'm able to see the changes made to the template files, but I don't actually see the view exported as part of the UG News view. Thank you! :)

**Comment by mmafe** [comment]
merged with sprint10 branch

**Pull request merged**
