### PR TITLE
Create 4-column News view for homepage

### PR DESCRIPTION
**Pull request by tqureshi-uog**

### CODE REVIEW

**Comment by tqureshi-uog** [comment]
See https://dev.web.uoguelph.ca/tqdev/ for working example. To test on a different dev site, create News items with Featured Images, and then add the View Pane **N4 - Recent news teaser (bootstrap layout)** to a panel page

**Comment by mmafe** [comment]
Last thing is that the N4 view panes appear to have different configuration options now. 

Recommend updating configuration options to be consistent. 

**Configuration for N4 with summary text**
image

**Configuration for N4 without summary text - allows changing of a more link and num items**
image

**Comment by tqureshi-uog** [comment]
@mmafe Change made - ok to merge now?

**Comment by mmafe** [comment]
Looks like neither more link is actually operational. Is the more link something we want to enable on both?

**Pull request merged**
