### PR TITLE
Feature ft3 random - Provides random teaser listing of FT3

### PR DESCRIPTION
**Pull request by mmafe**
No specific issue in github associated.

Provides a (separate content pane) for Featured Item teaser list sorted randomly. Site managers can add the view pane via the in place editor.

Solves the following: https://trello.com/c/D22jfzWE/246-1-ft3-featured-item-teaser-list-development-site-manager-needs-ability-to-change-order-of-items-from-asc-des-to-random-0-5

### CODE REVIEW

**Comment by mmafe** [comment]
@jpinsent @enichol Hey guys, could one of you confirm that this has been tested and works as required?

**Comment by jpinsent** [comment]
Tested & appears to be working as intended. Displays a teaser of 3 randomly selected featured items.

There is one inconsistency when using the Panels in Place editor, but it is not part of the spec. On the random content pane, nothing can be customized. On the default FT3 pane, the title can be overridden, the category can be specified and the number of items shown can be set.

Other than these missing customization options, the feature is working fully as intended.
https://trello.com/c/urrwVEuz

**Comment by mmafe** [comment]
@jpinsent Added panel overrides for category, more link, more text, title, items per page to the random ft3 view.

No results behaviour for FT3 is being handled by branch "issue238" -- once merged, the behaviour should be consistent for both the random and regular (asc/des) panels.

**Comment by jpinsent** [comment]
The 'More Features' button is not appearing on the Random view for FT3. The category override also only works with the category name as opposed to the category ID. Not sure if these are intended to be fixed upon the merge.

It is also still inconsistent with the regular view for FT3. The Random view has a check box to 'Provide a "more" link' and there is an option to 'Override "more" text', which are not present in the regular view.

**Comment by mmafe** [comment]
Instead of merging with develop, we're merging with release20151215 now. Closing this pull request. For further information see:

**Comment by mmafe** [comment]
Branch has been merged with sprint7_20160118 for testing/demo purposes.

**Comment by mmafe** [comment]
Merged with sprint8

**Comment by mmafe** [comment]
Merged with sprint9 branch.

**Comment by mancusop** [comment]
FT3 - Random:
Tested & appears to be working as intended. Displays a teaser of 3 randomly selected featured items.
In Place panels can override title, number of items shown, and filter by category.

- Tested on sandbox_pj

**Pull request merged**
