### PR TITLE
Fix: Make #ug-header focusable with tabindex="-1" (G6)[fixes #273]

### LINKED ISSUE #273: G6 - Global nav menu-items are not being read out in Narrow view with NVDA 2015.4/Chrome (Develop Branch)
After updating to the newest version of NVDA -- NVDA 2015.4, I could no longer hear the global menu items on dev sites using the develop branch when listening via screen reader.

Occurs under the following conditions:

- Google Chrome
- NVDA 2015.4
- Global menu is open

On a dev site using the develop branch, e.g. https://aoda.web.uoguelph.ca/ccs/

1. Refresh page
2. Click the URL bar
3. Resize the page to narrow (responsive) width
4. Tab to the global navigation toggle
5. Open the global navigation toggle
6. Tab down through the global navigation menu

Do the same on the production site using the master branch, https://www.uoguelph.ca/ccs/

### PR DESCRIPTION
**Pull request by mmatthews**

### CODE REVIEW

**Comment by mmafe** [comment]
Demoed and worked well. However, we are going to test this further on Voiceover, NVDA with Firefox, and JAWS.

**Comment by mmafe** [comment]
Merged with sprint9 branch.

**Comment by JProxxi** [comment]
Tested with NVDA (Chrome / FF), Voiceover, & JAWS. No new issues present

**Comment by mmafe** [comment]
Including the following note, so the issue is updated when the pull request is merged into develop.

Fixes #273.

**Pull request merged**
