### PR TITLE
[Master] Iss632 ft2

### PR DESCRIPTION
**Pull request by bdavey07**
Fixes issue #632

### CODE REVIEW

**Comment by nevantan** [comment]
[(2) #632 FT2 - Allow feature item listing page to be filtered by keyword/tag (in addition to category)](https://trello.com/c/SG2lMlVW/2174-2-632-ft2-allow-feature-item-listing-page-to-be-filtered-by-keyword-tag-in-addition-to-category)

**Comment by bdavey07** [comment]
Note: also changed so that title reads "Features related to <tag>"

**Comment by bdavey07** [comment]
@nevantan Fixed double title issue, starting automated tests now

**Comment by brharp** [comment]
FT3 should also be updated to allow filtering by either category or keyword terms.

**Comment by brharp** [comment]
When FT3 is filtered by category, the "more" link goes to features/category/[tid]. This should be changed to use the new path (features/[tid]).

**Pull request closed without merging**
