### PR TITLE
Change list of links to "jump" (select) list.

### PR DESCRIPTION
**Pull request by brharp**
Fixes issue #299

### CODE REVIEW

**Comment by jpinsent** [comment]
This has been tested and appears to be working as intended.

news archive dropdown

**Comment by mmafe** [comment]
Could we remove the number of associated nodes from the list? It could be confusing to hear December 2015 54 on a screenreader without any context on what that number means.

**Comment by mmafe** [comment]
Branch has been merged with sprint7_20160118 for testing/demo purposes.

**Comment by mmafe** [comment]
Merged with sprint8

**Comment by mmafe** [comment]
Merged with sprint9 branch.

**Comment by mancusop** [comment]
@mmafe  This has been tested and works as attended as per Feature Dev board https://trello.com/c/MjnMHfxJ/21-n5b-browse-news-by-date-select-menu

Feature has **failed** the accessibility testing due to missing label, unsure if it can be ignored.
- the "Select Month" textbox form control is missing a label element.

Added Accessibility report to https://trello.com/c/MjnMHfxJ/21-n5b-browse-news-by-date-select-menu

## Development Notes:
- Although requested by @mmafe - number of associated nodes has not been removed from list, screenreaders read the entire line such as "January 2016 3" which may be considered confusing.

**Comment by mmafe** [comment]
merged with sprint10 branch

**Comment by mmafe** [comment]
merged with sprint11 branch

**Comment by mmafe** [comment]
merged with sprint12 branch

**Pull request closed without merging**
