### PR TITLE
Pg3 page item more link

### PR DESCRIPTION
**Pull request by abanuog**
modified the "more" link for the view, to show either /pages or /pages/category/#

### CODE REVIEW

**Comment by mmafe** [comment]
Branch has been merged with sprint7_20160118 for testing/demo purposes.

**Comment by mmafe** [comment]
Merged with sprint8

**Comment by mmafe** [comment]
Merged with sprint9 branch.

**Comment by mancusop** [comment]
- Enabled pg3 on personal sandbox homepage. 
- Tested and works as described. 
- "more" link works for both category filtering and default /pages.

**Pull request merged**
