### PR TITLE
Iss767 update fontawesome to v3.7 module and v5.2 library

### PR DESCRIPTION
**Pull request by mmafe**
# Changes
- updated the makefile to use the latest version of the module(v3.7) and library(5.2)
- updated S1 (Share this Page) to use .fab class instead of .fa
- updated S3, S4, and S6 to use .fab class except for rss which uses .fa class (If adding a new icon to the Social Media content type which does not use .fab, remember to add the icon name to the ```$fa_icons``` array in the ```process_icon_bundle()``` function in the template.php file)
- added UG Font Awesome feature with default configuration for Font Awesome (uses Web Fonts with CSS)

# Release Instructions
- For new sites, UG Font Awesome will be enabled by default.
- For existing sites, there is an update_hook which enables the feature.
- If you cannot enable UG Font Awesome on a site, you can manually apply the change by navigating to /admin/config/content/fontawesome and ensuring "Web Fonts with CSS" is selected

# Testing
- check that the old icons still work, and that new ones do as well for Share This Page, Follow Us (both S3 and S4 versions), and Directory (S6)
- check that Font Awesome icons in the footer are not broken
- check that Font Awesome configuration has "Web Fonts with CSS" selected

### CODE REVIEW

**Comment by mmafe** [comment]
Tested as follows:
- Staged UAIC and Parking. Once UG Font Awesome is turned on, icons work
- Created a new site installation - icons worked.

**Comment by brharp** [comment]
It would be nice to have an update hook in ug profile that automatically enables the new ug_fontawesome feature. It's not essential---the release instructions work and are a perfectly acceptable. But if there is time, automatically enabling the feature would be a bonus.

**Comment by brharp** [comment]
The SVG icons have different spacing/padding than the CSS icons. For example:

Web Fonts with CSS:
image

SVG with JS:
image

The difference is due to a non breaking space that we always insert within the icon tag:
image

When the .fa element is removed from the DOM and replaced with SVG, the &nbsp; is also removed.

The &nbsp; is not added for layout, it's there to prevent CKEditor from deleting the otherwise "empty" tag. It just happens to also insert a bit of space between the icon and any text that follows.

I won't defend the &nbsp; hack as good design, but I imagine people have come to depend on it for layout. Removing it will be a change. I would suggest we need to:

- add a right margin to the inserted SVG to compensate for the removed space,
- change (manually?) the markup used for icons to include a space (e.g. `<span class="fa ...">&nbsp;</span>&nbsp;` (ick)), or
- mention this in the release notes, so site owners are at least aware of the change

Alternatively, instead of using SVG with JS, we can configure the Font Awesome module to insert icons the old way (Web Fonts with CSS). The drawback to this approach is there is no version 4 backwards compatibiilty. We would have to go back and update icons that are using the version 4 naming scheme (e.g. `fa fa-snapchat` becomes `fab fa-snapchat`). For things like the social media / follow us icons, we can update all of these in one place (in the feature). Icons in user content will be broken until fixed manually.

**Comment by mmafe** [comment]
**Next steps**
- Update the ug_fontawesome configuration so we use "Web Fonts with CSS". Remember to remove any unnecessary variables (e.g. the shim checkbox is unnecessary now)
- Update the Share this Page and Find us on Social Media icons so the brands use .fab instead .fa (note: the LinkedIn icon has a different name as well)

**Comment by mmafe** [comment]
Fixes #767

**Pull request merged**
