### PR TITLE
Update: added feeds to N3, E3, FT3 [refs #262]

### PR DESCRIPTION
**Pull request by abanuog**

### CODE REVIEW

**Comment by mmafe** [comment]
merged with sprint10 branch

**Comment by mmafe** [comment]
merged with sprint11 branch

**Comment by mmafe** [comment]
merged with sprint12 branch

**Comment by brharp** [comment]
@abanuog This branch has more than just the additional feed displays in it. There are also changes to the no results behaviour, etc. Could you please resubmit with only the addition of the feed displays, and add some tests?

**Pull request closed without merging**
