### PR TITLE
Fix: Anchors (Including skip to main content) don't work in Chrome [r…

### PR DESCRIPTION
**Pull request by abanuog**
…efs #27]

### CODE REVIEW

**Comment by mmafe** [comment]
merged with sprint10

**Comment by mmafe** [comment]
merged with sprint11 branch

**Comment by mmafe** [comment]
merged with sprint12 branch

**Comment by abanuog** [comment]
This bug has been fixed in the latest version of Chrome, so no need to merge this into our platform:
https://bugs.chromium.org/p/chromium/issues/detail?id=454172

**Comment by abanuog** [comment]
We decided to leave this fix out of the platform, as Chrome has addressed the bug in a newer release.

----- Original Message -----

**Pull request closed without merging**
