### PR TITLE
Issue 197 - change page title to match pane

### LINKED ISSUE #197: E13 - Page title does not identify contents (i.e. Events related to [keyword])
Similar to resolved issue #146. The listing page for events filtered by keyword is titled "Upcoming Events". 

https://aoda.web.uoguelph.ca/aodademo/events/70 

While a heading does appear above the content stating which keyword is being searched, an ambiguous page title fails WCAG 2.0 criterion 2.4.2. This issue must be resolved for this feature to be considered accessible.

### PR DESCRIPTION
**Pull request by morganrees9**
Fixes #197

Pulls page title from events view pane (E1), overrides E1 title to be blank, and overrides title for /events page to "Upcoming Events"

## Test Procedure

1. Check that generic "Upcoming Events" page title is showing at sitename/events.
2. Filter events by an existing term --> sitename/events/[term ID]. 
3. Check to see that the page title is now "Events related to [term name]"

screenshot-localhost-2017-04-13-11-34-56

### CODE REVIEW

**Comment by nevantan** [comment]
Testcafe test added in ccswbs/testing#10.

**Comment by nevantan** [comment]
Passing to @bdavey07 as I was a developer on this issue.

**Comment by bdavey07** [comment]
# Testing
## Manual Testing
1. Generate Event Category terms
2. Generate tags
3. Generate Events
4. Go to /events
    - Title is "Upcoming Events"
5. Go to each of the TIDs for the Event Categories
    - Title is "Events related to <Category Term Name>"
6. Go to each of the TIDs for the tags
    - Title is "Events related to <Tag name>"

## Automated Testing: Testcafe
- Testcafe test for this issue exists in ccswbs/testing/pull/10 
- Started with fresh install
- Works as described
- Adequately tests issue

## Automated Testing: Simpletest (In Progress)
- Running tests

## Additional Notes
- Unrelated to this issue, but, we currently cannot filter the "This week" or "Monthly Calendar" tabs by term ID, the tabs show all events that fall in this week and this moth respectively not matter what TID argument is given. 
- Also unrelated to this issue, but, we also cannot currently filter the "Past events" tab by term ID, the tab shows no events when given any TID as an argument.

**Comment by nevantan** [comment]
Event titles need to be <h2> when filtered by tid.

**Comment by nevantan** [comment]
views-view-fields--e1.tpl.php

**Comment by nevantan** [comment]
See ccswbs/hjckrrh#738.

**Pull request closed without merging**
