### PR TITLE
Updates to ug_service and ug_service_layouts features

### PR DESCRIPTION
**Pull request by tqureshi-uog**
**Changelog:**

- Bootstrap tabs enabled for Service details field collection
- "Service audience", "Related services", and "Find related services by keyword" moved to right sidebar and given bootstrap panel appearance
- New field "Call to action" added to Service content type. Appears in right sidebar by default and is intended for promo/buttons (e.g. "Request Service", "Request Support", etc)

End result should look like this: https://dev.web.uoguelph.ca/tqdev/service/lynda (you would need to add the button code manually in the "Call to action" longtext field)

### CODE REVIEW

**Comment by brharp** [comment]
In mobile view, the tabs jump around as the focus changes. May not be an issue, as on mobile devices your don't typically see hover events, but I thought I would mention it.

image

image

image

**Comment by tqureshi-uog** [comment]
@brharp This happens with Profile tabs as well: https://www-stage.uoguelph.ca/nursing/people/dr-hannah-foster - so it appears to be an issue with Bootstrap tabs itself

**Comment by brharp** [comment]
When I update the feature, I get some strange spacing between the tabs and the top border:

image

How did you fix this on your dev site?

**Comment by tqureshi-uog** [comment]
Oh, I forgot to commit that part. By default any content that has the `detail-page` class gets a larger bottom margin:

`.detail-page .main-container .middle li, .detail-page .main-container .col-sm-8 li {
    margin: 0 0 .643em 0;
}`

...so I had to use CSS injector on my dev site to override it. I've now committed that change to base.css so if you do another git pull and clear caches, the gap should be fixed (this problem didn't occur with Profile tabs because Profiles don't have the `detail-page` class, while Services do).

**Comment by dw235** [comment]
AHL fields will remain unchanged so long as UG Service catalogue is not reverted.

**Pull request merged**
