### PR TITLE
updated file_entity to 2.39

### PR DESCRIPTION
**Pull request by abanuog**
Security update for file_entity to 2.39

### CODE REVIEW

**Review by mmafe — CHANGES_REQUESTED** [review]
It looks like the feeds_ex and smtp modules are being updated as well (although smtp appears to be going to an older version). Can you confirm that extra changes were not accidentally added to the commit?

**Comment by abanuog** [comment]
Those got updated automatically when running make...not sure why.

**Comment by tqureshi-uog** [comment]
I believe there's something wrong with the make file itself - it looks like it wasn't updated at the time we deployed[ an upgrade to the smtp module](https://teams.microsoft.com/l/message/19:8ddcdd248c0d4f3385fb16f7400043dc@thread.skype/1685458893236?tenantId=be62a12b-2cad-49a1-a5fa-85f4f3156a7d&groupId=4b276b63-bfd2-43ea-a73c-69acde47826f&parentMessageId=1685458893236&teamName=CCS%20Web%20%26%20Development%20Solutions&channelName=Maintenance%20Lead&createdTime=1685458893236) last year. On my local copy of hjckrrh, I changed `projects[smtp][version] = "1.7"` to `projects[smtp][version] = "1.9"` and re-ran the make command which resulted in it leaving the smtp files alone. However, the feeds module files still got changed and I haven't been able to determine if it's due a similar reason.

For now, I would recommend removing all the feeds_ex and smtp module files from this pull request.

**Review by mmafe — CHANGES_REQUESTED** [review]
I agree with Tanya that we should limit the commits to those related to the file_entity module.

Recommend we:
- Remove feeds_ex from the makefile. 
- Commit /profiles/ug/drupal-org.make
- Commit /sites/all/modules/file_entity

That way you can proceed with the security update and we can take more time to look into the other two modules. (Ideally I'd like to disable feeds_ex if we can due to its lack of security coverage and find out what data layer is being used for).

**Comment by abanuog** [comment]
@mmafe So, I should remove datalayer from the makefile, along with feeds_ex.

**Comment by mmafe** [comment]
Recommending we don't remove datalayer until we confirm it's no longer needed.

**Pull request closed without merging**
