### PR TITLE
Iss548 printstylesheet

### LINKED ISSUE #548: G0 - Set up a print stylesheet for the platform
Stylesheet should hide any unnecessary content and print all text in a large, readable font. Use HR as an example.

### PR DESCRIPTION
**Pull request by ljairath**
Fixes #548

### CODE REVIEW

**Comment by brharp** [comment]
Looks good, just need to review the "manage display" settings for other content types.

**Comment by brharp** [comment]
I added the print module and tcpdf library to drupal-org.make, and cleaned up some .svn directories from the libraries folder.

**Comment by brharp** [comment]
@ljairath When printing news articles, I don't think we need a label on "Feature image caption". We probably don't need to see the "external link" either (usually, if an article has an external link we will never get to print it anyways).

**Comment by brharp** [comment]
@ljairath When printing FAQ the "posted by" line and "Answer" label are probably not necessary.

**Comment by brharp** [comment]
@ljairath The print layout for course outlines doesn't match the screen layout. The screen layout is:

- Title
- Code and section
- Term
- Instructor
- Details
- Syllabus
- Website

Could we try to have the print layout more aligned with the screen layout?

**Comment by brharp** [comment]
Although the default layout for profiles does not include the print button, profiles should still print properly (the print link could be added to the layout for any node type). Currently, the print layout for profiles does not include the same fields as the screen layout (in particular, the 'profile sections' are missing).

**Comment by brharp** [comment]
Print layout for services could use some work as well.

**Comment by nevantan** [comment]
Add, Edit, and Delete links removed from the content types that had them.

**Comment by brharp** [comment]
capture

@nevantan I get the following errors when running unit tests after merging this branch. Can you please try running the "UG" tests and let me know if you get the same errors?

**Comment by tqureshi-uog** [comment]
Resolved in https://github.com/ccswbs/hjckrrh/pull/613

**Pull request closed without merging**
