### PR TITLE
Update UG installation profile

### PR DESCRIPTION
**Pull request by mmatthews**
I've updated the UG profile to include a few more modules that will be enabled when creating a site.

### CODE REVIEW

**Comment by mmafe** [comment]
Received a potential conflict when attempting to merge with sprint7_20160118.

```
error: The following untracked working tree files would be overwritten by checkout:
	sites/all/modules/module_filter/CHANGELOG.txt
	sites/all/modules/module_filter/LICENSE.txt
	sites/all/modules/module_filter/README.txt
	sites/all/modules/module_filter/css/dynamic_position.css
	sites/all/modules/module_filter/css/module_filter.css
	sites/all/modules/module_filter/css/module_filter_tab-rtl.css
	sites/all/modules/module_filter/css/module_filter_tab.css
	sites/all/modules/module_filter/css/modules.css
	sites/all/modules/module_filter/css/update_status.css
	sites/all/modules/module_filter/js/dynamic_position.js
	sites/all/modules/module_filter/js/module_filter.js
	sites/all/modules/module_filter/js/module_filter_tab.js
	sites/all/modules/module_filter/js/modules.js
	sites/all/modules/module_filter/js/permissions.js
	sites/all/modules/module_filter/js/update_status.js
	sites/all/modules/module_filter/module_filter.admin.inc
	sites/all/modules/module_filter/module_filter.info
	sites/all/modules/module_filter/module_filter.install
	sites/all/modules/module_filter/module_filter.module
	sites/all/modules/module_filter/module_filter.pages.inc
	sites/all/modules/module_filter/module_filter.theme.inc
	sites/all/modules/pathauto/INSTALL.txt
	sites/all/modules/pathauto/LICENSE.txt
	sites/all/modules/pathauto/README.txt
	sites/all/modules/pathauto/pathauto.admin.inc
	sites/all/modules/pathauto/pathauto.api.php
	sites/all/modules/pathauto/pathauto.inc
	sites/all/modules/pathauto/pathauto.info
	sites/all/modules/pathauto/pathauto.install
	sites/all/modules/pathauto/pathauto.js
	sites/all/modules/pathauto/pathauto.module
	sites/all/modules/pathauto/pathauto.pathauto.inc
	sites/all/modules/pathauto/pathauto.test
	sites/all/modules/pathauto/pathauto.tokens.inc
Please move or remove them before you can switch branches.
Aborting
```
Let's hold off on merging this into the sprint/demo branch until we have time to investigate.

**Comment by mmafe** [comment]
Successfully merged with sprint7_20160118.

Ended up discarding my local copies of pathauto and module_filter by doing a force checkout followed by a merge.

**Comment by mmafe** [comment]
Merged with sprint8

**Comment by mmafe** [comment]
Merged with sprint9 branch.

**Comment by JProxxi** [comment]
tested: new modules were enabled on install, no new issues present on site.

**Comment by mmatthews** [comment]
@mmafe 
Any idea when this will be merged to master? Would be nice to have on the client environment (module_filter, pathauto, etc.)

**Comment by mmafe** [comment]
Whenever next release occurs. Likely next Tuesday.

**Pull request merged**
