### PR TITLE
Recreated branch / pull request for UG Profile feature

### PR DESCRIPTION
**Pull request by brharp**
Fixes issue #314

### CODE REVIEW

**Comment by mmafe** [comment]
Merged with sprint11 branch for testing purposes.

**Comment by mancusop** [comment]
@mmafe anyone assigned to testing?

**Comment by brharp** [comment]
Formatting of unusually long field values I don't really consider a bug. The formatting of the page does not break, even for unreasonably long data for names, phone numbers, etc. The maximum values for these fields were given in the spec, and I don't really see any other way to accommodate large values other than to have lines wrap, etc. I don't think truncating the data is an option. For reasonably values, the formatting looks good, for unreasonable data the formatting works and is legible.

**Comment by brharp** [comment]
Problems with sorting by name and name display have been fixed by enabling auto_nodetitle module.

**Comment by mancusop** [comment]
@mmafe @brharp Created a11y report - feature fails due to multiple validation errors found on listing pages. 

4.1.1 Parsing failed - examples:
* Error: "Element figure not allowed as child of element span in this context."
* Error: "Duplicate attribute class."

Validation links: 
https://validator.w3.org/nu/?doc=https%3A%2F%2Faoda-test.web.uoguelph.ca%2Fsandbox_pj%2Fpeople%2Ffaces

https://validator.w3.org/nu/?showsource=yes&doc=https%3A%2F%2Faoda-test.web.uoguelph.ca%2Fsandbox_pj%2Fpeople#cl466c30

Report is uploaded on Trello:
https://trello.com/c/TmvKHj4D/123-people-profiles-overview

**Comment by mancusop** [comment]
@brharp @mmafe everything else appears to work as intended and passes a11y checks.

**Comment by mmafe** [comment]
merged with sprint12 branch

**Comment by mmafe** [comment]
Thanks for testing @mancusop!

I've added the issues to the issue tracker:
https://github.com/ccswbs/hjckrrh/issues/385
https://github.com/ccswbs/hjckrrh/issues/386

Since the issues are not show-stoppers, I'm going to merge ug_profile onto the develop branch. We can fix the validation issues in future.

**Pull request merged**
